services:
  db_litellm:
    image: postgres:15
    container_name: dataset_generator_postgres_litellm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: litellm
    ports:
      - "5433:5432"
    volumes:
      - pgdata_litellm:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d litellm"]
      interval: 5s
      timeout: 5s
      retries: 5

  db_metabase:
    image: postgres:15
    container_name: dataset_generator_postgres_metabase
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dataset_generator
    ports:
      - "5434:5432"
    volumes:
      - pgdata_metabase:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dataset_generator"]
      interval: 5s
      timeout: 5s
      retries: 5

  metabase:
    image: metabase/metabase:latest
    container_name: dataset_generator_metabase
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: dataset_generator
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: db_metabase
    depends_on:
      db_metabase:
        condition: service_healthy
    networks:
      - app-network

  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    container_name: dataset_generator_litellm
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - ./litellm-config.yaml:/app/config.yaml
    command:
      ["--config", "/app/config.yaml", "--port", "4000", "--num_workers", "8"]
    environment:
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY:-sk-1234}
      LITELLM_SALT_KEY: ${LITELLM_SALT_KEY:-sk-1234}
      DATABASE_URL: "postgresql://postgres:postgres@db_litellm:5432/litellm"
      STORE_MODEL_IN_DB: "True"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GOOGLE_GENAI_API_KEY: ${GOOGLE_GENAI_API_KEY}
      AZURE_API_KEY: ${AZURE_API_KEY}
    depends_on:
      db_litellm:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata_litellm:
  pgdata_metabase:
